// <auto-generated />
using BusinessData.ofCommon.ofKApt.ofDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessData.Migrations.KAptDb
{
    [DbContext(typeof(KAptDbContext))]
    partial class KAptDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, (int)1L, 1);

            modelBuilder.Entity("BusinessData.ofCommon.ofKapt.KAptBasicInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Container")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateofApprovalForUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Generalmanagementpersonnel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuardManagement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuardManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Housemanager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageofInfos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagementOfficeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagementOfficeFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagementOfficePhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Managementmanagementmethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Managementmethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberofApt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberofHouseHolds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numberofparkingspaces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numberofundergroundparkingspaces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegalAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Viliage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WelfareFacility")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KAptBasicInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
